num1 = int(input("Enter 1st number: "))
num2 = int(input("Enter 2nd number: "))
if num1==num2:print("The number is equal")
if num1>num2:print("The  1st number is greater")
else: print("The  2nd number is greater")
